# -*- coding: utf-8 -*-
"""INF8225 Projet BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1va8nshRhHwrSLIOyrcWt8Gq8MJz8LOPd

# Évaluation d'un modèle BERT pré-entraîné
basé sur https://aclanthology.org/2020.acl-main.391/#:~:text=2020.-,Encoder-Decoder%20Models%20Can%20Benefit%20from%20Pre-trained%20Masked%20Language,Models%20in%20Grammatical%25

# Installations et importations
"""

!wget https://raw.githubusercontent.com/kanekomasahiro/bert-gec/master/scripts/convert_m2_to_parallel.py
!wget https://raw.githubusercontent.com/kanekomasahiro/bert-gec/master/scripts/detok.py
!wget https://raw.githubusercontent.com/kanekomasahiro/bert-gec/master/scripts/generate.sh
!wget https://raw.githubusercontent.com/kanekomasahiro/bert-gec/master/scripts/setup.sh
!wget https://raw.githubusercontent.com/kanekomasahiro/bert-gec/master/scripts/train.sh

!pip install boto3

import shutil
import os

from google.colab import drive, files
drive.mount('/content/drive')

os.mkdir("/bert-fuse/")

shutil.copy("/content/drive/MyDrive/official-2014.combined.m2", "/content/")
shutil.copy("/content/drive/MyDrive/dict.src.txt", "/bert-fuse/")
shutil.copy("/content/drive/MyDrive/dict.trg.txt", "/bert-fuse/")
shutil.copy("/content/drive/MyDrive/checkpoint_best.pt", "/bert-fuse/")

"""# Génération des fichiers sources et cibles"""

!python convert_m2_to_parallel.py official-2014.combined.m2 output_src.txt output_tgt.txt

files.download('/content/output_src.txt')
files.download('/content/output_tgt.txt')

"""# BERT

## Préparation
"""

!sh setup.sh

!nvidia-smi

"""Certains des fichiers téléchargés utilisent des versions antérieures de numpy et de pytorch. Ils sont modifiés ici pour être comptatibles avec les versions à jour."""

# Remplacement de np.float par np.float64
with open("../bert-nmt/fairseq/data/indexed_dataset.py", "r+") as f:
  content = f.read()
  modified_content = content.replace("np.float", "np.float64")
  f.seek(0)
  f.write(modified_content)

# Les opérations entre les float et les bool ne sont plus supportées par pytorch
with open("../bert-nmt/fairseq/sequence_generator.py", "r+") as f:
  content = f.read()
  modified_content = content.replace("bert_outs, _ = model.models[0].bert_encoder(bertinput, output_all_encoded_layers=True, attention_mask= 1. - bert_encoder_padding_mask)",
                                     "bert_outs, _ = model.models[0].bert_encoder(bertinput, output_all_encoded_layers=True, attention_mask=~bert_encoder_padding_mask)")
  f.seek(0)
  f.truncate()
  f.write(modified_content)

# torch.div ne supporte plus l'assignation d'un float à un double
with open("../bert-nmt/fairseq/search.py", "r+") as f:
  content = f.read()
  modified_content = content.replace("torch.div(self.indices_buf, vocab_size, out=self.beams_buf)",
                                     "self.beams_buf = self.indices_buf // vocab_size")
  f.seek(0)
  f.truncate()
  f.write(modified_content)

"""## Génération des prédictions du modèle BERT"""

!sh generate.sh output_src.txt 0

files.download('../bert-fuse/output/test.best.src')
files.download('../bert-fuse/output/test.best.tok')
files.download('../bert-fuse/output/test.bpe.src')
files.download('../bert-fuse/output/test.cat.src')
files.download('../bert-fuse/output/test.nbest.src')