# -*- coding: utf-8 -*-
"""Évaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k50UKL7cjRxrwjZoTTM6XVq3MklRpQoM
"""

!pip install sacrebleu > /dev/null
import sacrebleu

!pip install torchmetrics > /dev/null
from torchmetrics.functional.text.rouge import rouge_score

from pprint import pprint

!pip install errant > /dev/null
!python3 -m spacy download en_core_web_sm > /dev/null

from google.colab import drive, files
drive.mount('/content/drive')

preds = None
with open('/content/drive/MyDrive/corrected_BART.txt', 'r') as f:
  preds = f.readlines()

truths = None
with open('/content/drive/MyDrive/output_tgt.txt', 'r') as f:
  truths = f.readlines()

bleu = sacrebleu.corpus_bleu(preds, [truths])
print(bleu)

pprint(rouge_score(preds, truths))

!errant_parallel -orig /content/drive/MyDrive/output_src.txt -cor /content/drive/MyDrive/output_tgt.txt -out truth.m2
!errant_parallel -orig /content/drive/MyDrive/output_src.txt -cor /content/drive/MyDrive/corrected_BART.txt -out bert_preds.m2
!errant_compare -hyp bert_preds.m2 -ref truth.m2

!errant_compare -hyp bert_preds.m2 -ref truth.m2 -dt

!errant_compare -h

!errant_parallel -h

!errant_compare -hyp bert_preds.m2 -ref /content/drive/MyDrive/official-2014.combined.m2